#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');

const JS_DIR = __dirname;
const ROOT = path.resolve(JS_DIR, '..');
const OUT = path.join(ROOT, 'agent.js');

const MODULE_ORDER = [
    'constants.js',
    'state.js',
    'utils/logger.js',
    'network/websocket.js',
    'network/http.js',
    'hooks/hooks.js',
    'game/game.js',
    'modules/inviter.js',
    'modules/spinner.js',
    'ui/ui.js',
    'ui/buttons.js',
    'ui/menus/trackerMenu.js',
    'ui/menus/inviterMenu.js',
    'ui/menus/boosterMenu.js',
    'ui/menus/spinnerMenu.js',
    'ui/menuController.js',
    'index.js'
];

function transform(src) {
    src = src.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

    const lines = src.split('\n');
    const result = [];

    let inBlockComment = false;
    let inMultiImport = false;
    let inMultiExportObj = false;

    for (let i = 0; i < lines.length; i++) {
        const raw = lines[i];
        const trimmed = raw.trim();

        if (inBlockComment) {
            result.push(raw);

            if (raw.includes('*/')) inBlockComment = false;

            continue;
        }
        if (trimmed.startsWith('/*')) {
            if (!trimmed.includes('*/')) inBlockComment = true;

            result.push(raw);

            continue;
        }

        if (trimmed.startsWith('//')) {
            result.push(raw);

            continue;
        }

        if (!inMultiImport && /^import\s*\{/.test(trimmed) && !trimmed.includes('}')) {
            inMultiImport = true;

            result.push('// [build] ' + trimmed);

            continue;
        }
        if (inMultiImport) {
            result.push('// [build] ' + trimmed);

            if (trimmed.includes('}')) inMultiImport = false;

            continue;
        }

        if (/^import\s*\{[^}]*\}\s*from\s*['"][^'"]*['"]\s*;?\s*$/.test(trimmed) ||
            /^import\s+\w[\w$]*\s+from\s*['"][^'"]*['"]\s*;?\s*$/.test(trimmed) ||
            /^import\s*['"][^'"]*['"]\s*;?\s*$/.test(trimmed)) {
            result.push('// [build] ' + trimmed);

            continue;
        }

        if (!inMultiExportObj && /^export\s*\{/.test(trimmed) && !trimmed.includes('}')) {
            inMultiExportObj = true;

            result.push('// [build] ' + trimmed);

            continue;
        }
        if (inMultiExportObj) {
            result.push('// [build] ' + trimmed);

            if (trimmed.includes('}')) inMultiExportObj = false;

            continue;
        }

        if (/^export\s*\{[^}]*\}\s*;?\s*$/.test(trimmed)) {
            result.push('// [build] ' + trimmed);

            continue;
        }

        if (/^export\s+default\s+/.test(trimmed)) {
            result.push(raw.replace(/^(\s*)export\s+default\s+/, '$1'));

            continue;
        }

        if (/^export\s+(const|let|var|function|class|async\s+function)\b/.test(trimmed)) {
            result.push(raw.replace(/^(\s*)export\s+/, '$1'));

            continue;
        }

        result.push(raw);
    }

    return result.join('\n');
}

function deduplicateTopLevel(src) {
    const seen = new Set();
    const lines = src.split('\n');

    return lines.map(line => {
        const isTopLevel = line.length > 0 &&
            line[0] !== ' ' &&
            line[0] !== '\t' &&
            line[0] !== '/';

        if (!isTopLevel) return line;

        const m = line.match(/^(const|let|var)\s+([\w$]+)/);

        if (!m) return line;

        const varName = m[2];

        if (seen.has(varName)) return '// [build:dedup] ' + line.trim();

        seen.add(varName);

        return line;
    }).join('\n');
}

console.log('\nBuilding agent.js...\n');

const header = [
    '// ============================================================',
    '// agent.js — auto-generated by js/build.js',
    '// DO NOT EDIT MANUALLY. Source: js/ folder.',
    '// ============================================================',
    ''
].join('\n');

const chunks = [header];
let totalSourceLines = 0;

for (const rel of MODULE_ORDER) {
    const fullPath = path.join(JS_DIR, rel);

    if (!fs.existsSync(fullPath)) {
        console.error(`\n  ✗  MISSING: ${rel}\n`);

        process.exit(1);
    }

    const raw = fs.readFileSync(fullPath, 'utf8');
    const transformed = transform(raw);
    const lineCount = raw.split('\n').length;

    totalSourceLines += lineCount;

    chunks.push(
        `\n// ${'─'.repeat(58)}`,
        `// ${rel}`,
        `// ${'─'.repeat(58)}`,
        transformed
    );

    console.log(`  ✓  ${rel.padEnd(42)} ${String(lineCount).padStart(4)} lines`);
}

let output = deduplicateTopLevel(chunks.join('\n'));

const leaked = output.split('\n').filter(l => {
    const t = l.trim();

    return !t.startsWith('//') && /^(import|export)\s/.test(t);
});

if (leaked.length > 0) {
    console.warn('\n  ⚠  WARNING: leaked import/export statements:');

    leaked.slice(0, 10).forEach(l => console.warn('     ' + l.trim()));

    if (leaked.length > 10) console.warn(`     ... and ${leaked.length - 10} more`);
}

fs.writeFileSync(OUT, output, 'utf8');

const outLines = output.split('\n').length;

console.log(`\n  Source : ${totalSourceLines} lines`);
console.log(`  Output : ${outLines} lines  →  ${OUT}`);
console.log(`  Status : ${leaked.length === 0 ? 'OK ✓' : 'WARN (' + leaked.length + ' leaked)'}`);
console.log('');
